### PR TITLE
Move from circleci to github workflows

### PR DESCRIPTION
**Pull request by yikeke**
### What is changed, added or deleted? (Required)

Fix: https://github.com/tidbcloud/dbaas-docs/pull/17, https://github.com/tidbcloud/dbaas-docs/pull/22 (Remove multiple inapplicable issue links from release notes)

NOTES:

1. Repos that have zh/en folders and use relative internal links should use github workflows/actions instead of circleci.
2. Check scripts might need modification because they are some repo-specific code and conditions.
3. #17, #22, #23 have complete configs for integrating markdownlint, link (internal + external), anchor checks.

### CODE REVIEW

**Comment by yikeke** [comment]
PTAL at this [commit](https://github.com/tidbcloud/dbaas-docs/pull/23/commits/bf93462de569b68f204fa3980282c6c5c74ddf7f). @lilin90

**Comment by lilin90** [comment]
> PTAL at this [commit](https://github.com/tidbcloud/dbaas-docs/pull/23/commits/bf93462de569b68f204fa3980282c6c5c74ddf7f). @lilin90

LGTM

**Comment by yikeke** [comment]
cc @lilin90

**Comment by yikeke** [comment]
@sykp241095 @YiniXu9506 PTAL

**Review by lilin90 — APPROVED** [review]
LGTM

**Review by tennix — APPROVED** [review]
LGTM

**Pull request merged**
